# Generated by Django 6.0.6 on 2026-07-02 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('contact', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModeleBoitier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDefaut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boitier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('etat', models.CharField(choices=[('stock', 'En stock'), ('installe', 'Installé'), ('panne', 'En panne'), ('retire', 'Retiré')], default='stock', max_length=20)),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boitiers', to='equipements.modeleboitier')),
            ],
        ),
        migrations.CreateModel(
            name='CarteSIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(max_length=30, unique=True)),
                ('numero_telephone', models.CharField(blank=True, max_length=30)),
                ('etat', models.CharField(choices=[('active', 'Active'), ('suspendue', 'Suspendue'), ('resiliee', 'Résiliée')], default='active', max_length=20)),
                ('date_activation', models.DateField(blank=True, null=True)),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartes_sim', to='equipements.operateur')),
            ],
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('est_administrateur', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JournalModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele_concerne', models.CharField(max_length=50)),
                ('objet_id', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('technicien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipements.technicien')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_installation', models.DateField()),
                ('date_desinstallation', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('boitier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='equipements.boitier')),
                ('carte_sim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='equipements.cartesim')),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='equipements.technicien')),
            ],
            options={
                'ordering': ['-date_installation'],
            },
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origine', models.CharField(choices=[('terrain', 'Signalé sur le terrain'), ('atelier', 'Découvert en atelier')], default='terrain', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='equipements.installation')),
                ('signale_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostics_signales', to='equipements.technicien')),
                ('defauts', models.ManyToManyField(related_name='diagnostics', to='equipements.typedefaut')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaque', models.CharField(max_length=20, unique=True)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='equipements.client')),
            ],
        ),
        migrations.AddField(
            model_name='installation',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='equipements.vehicule'),
        ),
    ]
