# Generated by Django 6.0.6 on 2026-07-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='contact',
            new_name='telephone',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='client',
            name='prenom',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
