# Generated by Django 6.0.6 on 2026-07-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0002_rename_contact_client_telephone_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='marque',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
