# Generated by Django 6.0.6 on 2026-07-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0003_vehicule_marque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicien',
            old_name='contact',
            new_name='telephone',
        ),
        migrations.RemoveField(
            model_name='technicien',
            name='user',
        ),
        migrations.AddField(
            model_name='technicien',
            name='email',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='technicien',
            name='mot_de_passe',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='technicien',
            name='prenom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
