# Generated by Django 6.0.6 on 2026-07-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0004_rename_contact_technicien_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartesim',
            name='iccid',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='cartesim',
            name='numero_telephone',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
