# Generated by Django 6.0.6 on 2026-08-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0005_alter_cartesim_iccid_alter_cartesim_numero_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartesim',
            name='iccid',
        ),
    ]
